
services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - custom_bridge
    ports:
      - "8080:80"
    depends_on:
      - apache
    deploy:
      resources:
        limits:
          memory: 100M
          cpus: "0.5"

  apache:
    build:
      context: ./apache
    container_name: apache
    networks:
      - custom_bridge
    depends_on:
      - flask
    ports:
      - "9000:80"
    deploy:
      resources:
        limits:
          memory: 150M
          cpus: "0.7"

  flask:
    build:
      context: ./flask
    container_name: flask
    networks:
      - custom_bridge
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: "1.0"

  postgres:
    build:
      context: ./postgres
    container_name: postgres
    networks:
      - custom_bridge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 250M
          cpus: "1.0"

networks:
  custom_bridge:
    driver: bridge

volumes:
  postgres_data:
